version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - 'themes/custom'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'all'
    groups:
      dependencies:
        patterns: ['*']
