name: Test
on:
  pull_request_target:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
    ci:
        name: Build test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v4
              with:
                cache: npm
                cache-dependency-path: package-lock.json
            - run: npm ci
            - run: npm run build
